### ISSUE TITLE
More accent colors?

### ISSUE THREAD

**Issue by elkrien** [Fausto-Korpsvart/Catppuccin-GTK-Theme#1]
Great theme!
Any chance that You can do more accent colours / variants? Like Mocha Lavender, Mocha Green etc.
Also would be great to have more Catppuccin Flavours - Latte and Frappe :)
You should also submit theme to Catppuccin Organization - GTK theme which is there is no more developed and is not as good as Your one.

**Comment by Fausto-Korpsvart** [comment]
> Latte and Frappe

Hello @elkrien.

About the Latte and Frappé versions, those will come as soon as I fix some bugs in the white versions, but they will come.

About the possibility of different accent colour versions, well, I'm trying to respect the colour palette of the creators of each theme so far, but it's not a bad idea, so I'll do some testing and consider the idea of making those versions.

And yes, it would be great to put the theme within the Catppuccin organisation, I'll consider doing that when the theme is fully polished.

Thanks for the suggestion and for the support };-]

**Comment by WitherCubes** [comment]
Just ping me when you are done polishing and we can merge this upstream with [catppuccin/gtk](https://github.com/catppuccin/gtk).

**Comment by jh-devv** [comment]
+1
This would be cool!

**Comment by jh-devv** [comment]
@Fausto-Korpsvart What is the current like accent color thing, as an example if I would want to use Mocha Lavender?

**Comment by Fausto-Korpsvart** [comment]
@elkrien, @WitherCubes, @jh-devv
All variants of Catppuccin are now available with different accent colours, from the installer you can choose as you like.

I hope you enjoy the theme, and thank you for your support.
