### ISSUE TITLE
Add to Nixpkgs

### ISSUE THREAD

**Issue by jh-devv** [Fausto-Korpsvart/Catppuccin-GTK-Theme#12]
Hey!

It would be cool if this would be added to nixpgs, the official Catppuccin GTK theme is kinda broken, this seems to work much better!

**Comment by TropicLegend** [comment]
I have the same issue. The official Catppuccin GTK theme is also broken for me on nixos.
Is there currently a workaround?

**Comment by jh-devv** [comment]
> I have the same issue. The official Catppuccin GTK theme is also broken for me on nixos.

Yea, especially after the theme got archived, Colloid will be maintaining some variants upstream though?

**Comment by Fausto-Korpsvart** [comment]
> I have the same issue. The official Catppuccin GTK theme is also broken for me on nixos. Is there currently a workaround?

@TropicLegend, I'm working on it, I'm researching on how to add these themes to NixOS packages, I also want to add them to AUR and COPR, I just need some time and patience on your part, as I have to finish the rest of the themes only in my spare time.

Thanks for the suggestion, and when I'm ready to package the themes I'll let you know.

**Comment by Fausto-Korpsvart** [comment]
> Yea, especially after the theme got archived, Colloid will be maintaining some variants upstream though?

@jh-devv, yes, I noticed that the official theme has already been archived, that's why I wanted to contribute with this theme adding all the variants.

Regarding the Colloid theme, I have no idea if Catppuccin has been added to its colour palettes, but you can ask the developer of the Colloid theme to find out about that.

**Comment by Icy-Thought** [comment]
Forgot to comment here but I have a working nixpkg for this theme in my personal repository. I might push it to upstream either tomorrow or the day after!

**Comment by Airradda** [comment]
> Regarding the Colloid theme, I have no idea if Catppuccin has been added to its colour palettes, but you can ask the developer of the Colloid theme to find out about that.

It appears to have a Catppuccin color palette, which was added in response to [this issue](https://github.com/vinceliuice/Colloid-gtk-theme/issues/167). You can find it in [this commit](https://github.com/vinceliuice/Colloid-gtk-theme/commit/9ffb38b5a10a7900b50cbf0cb7cbf62cc1e2103c), a preview at the bottom of the [color schemes image](https://github.com/vinceliuice/Colloid-gtk-theme#colorschemes), and it is available in the Nix package under [`tweaks`](https://github.com/NixOS/nixpkgs/blob/2893f56de08021cffd9b6b6dfc70fd9ccd51eb60/pkgs/data/themes/colloid-gtk-theme/default.nix#L21).

**Comment by Fausto-Korpsvart** [comment]
> It appears to have a Catppuccin color palette, which was added in response to [this issue](https://github.com/vinceliuice/Colloid-gtk-theme/issues/167). You can find it in [this commit](https://github.com/vinceliuice/Colloid-gtk-theme/commit/9ffb38b5a10a7900b50cbf0cb7cbf62cc1e2103c), a preview at the bottom of the [color schemes image](https://github.com/vinceliuice/Colloid-gtk-theme#colorschemes), and it is available in the Nix package under [`tweaks`](https://github.com/NixOS/nixpkgs/blob/2893f56de08021cffd9b6b6dfc70fd9ccd51eb60/pkgs/data/themes/colloid-gtk-theme/default.nix#L21).

@Airradda, so there is already an option, and I see that some of the colour palettes I started to implement have been added, when I knew the `Colloid` theme only had the original palette, `Nord` and `Dracula`, now it has many more, it's great.

I still have to do some more research on how to make the packs for `NIXPKGS`, `AUR` and `COPR`, but due to my work I can only dedicate my free time to these projects, but I will do it, as soon as possible I will start to create the packs too.

Thanks for the information and support.

**Comment by Fausto-Korpsvart** [comment]
> Forgot to comment here, but I have a working nix package for this theme in my personal repository. I might push it to upstream either tomorrow or the day after!
> 
> EDIT: One thing that we need to do though is to add some form of tagging system or release cycle to the theme repositories of yours @Fausto-Korpsvart. It will help reduce the burden of constantly updating the commit revision when trying to update the packages.

Yes, I have to look for more information on this topic to get more involved and to know how this whole packaging system works.

Thanks for your support and for the suggestion, I will take it into account }:]

**Comment by jh-devv** [comment]
> Forgot to comment here, but I have a working nix package for this theme in my personal repository. I might push it to upstream either tomorrow or the day after!

Did the same with my personal flake :3

**Comment by Brisingr05** [comment]
Most GTK and icon themes from @Fausto-Korpsvart have already been packaged in `nixpkgs`:

1. [Kanagawa](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/ka/kanagawa-gtk-theme/package.nix)
2. [Everforest](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/ev/everforest-gtk-theme/package.nix)
3. [Gruvbox](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/gr/gruvbox-gtk-theme/package.nix)
4. [Nightfox](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/ni/nightfox-gtk-theme/package.nix)
5. [Tokyonight](https://github.com/NixOS/nixpkgs/tree/nixos-unstable/pkgs/data/themes/tokyonight-gtk-theme)

**Comment by Icy-Thought** [comment]
@Brisingr05, the new format is quite different than the old one and therefore we need to rework the tokyonight implementation. (don't know about the rest, did not check)

**Comment by Icy-Thought** [comment]
Package was recently merged into nixpkgs. You can now close the issue! ;)
