### ISSUE TITLE
Add Gnome 45 support

### ISSUE THREAD

**Issue by LeRatGondin** [Fausto-Korpsvart/Catppuccin-GTK-Theme#16]
**Issue Description:**
The Catppuccin GTK Theme is currently not compatible with Gnome 45, and some elements, such as Nautilus, do not display the expected appearance. The provided screenshot illustrates the issue: 
![Capture d’écran du 2024-02-27 14-53-23](https://github.com/Fausto-Korpsvart/Catppuccin-GTK-Theme/assets/44407018/0dc4ebfc-d833-4cce-9bdd-799d75119e21)

Please update the Catppuccin GTK Theme to ensure compatibility with Gnome 45.

**Comment by Fausto-Korpsvart** [comment]
@LeRatGondin, I'm already working on it, there will be updates for this and the other themes soon.
