### ISSUE TITLE
unreadable text in gnome files

### ISSUE THREAD

**Issue by Rishabh-Sarang** [Fausto-Korpsvart/Catppuccin-GTK-Theme#21]
![Screenshot from 2024-08-26 15-04-17](https://github.com/user-attachments/assets/306ba1a3-9ca6-4f9e-afb0-b0eaed4c68b6)
![ll](https://github.com/user-attachments/assets/9404bbcf-9783-4dff-92fc-69fd3eec3fcc)

try to look at the transfers speed below progress bar

**Comment by Fausto-Korpsvart** [comment]
Thanks for reporting, I'll take a look and fix and update as soon as possible.

**Comment by Rishabh-Sarang** [comment]
> Thanks for reporting, I'll take a look and fix and update as soon as possible.

any update?

**Comment by Fausto-Korpsvart** [comment]
> any update?

It's already updated, you can test it and let me know if anything is wrong.
