### ISSUE TITLE
text visibility

### ISSUE THREAD

**Issue by Rishabh-Sarang** [Fausto-Korpsvart/Catppuccin-GTK-Theme#23]
![image](https://github.com/user-attachments/assets/81c5870e-bd67-4124-a945-afa466e43780)

text not visible in gnome settings search results

**Comment by Fausto-Korpsvart** [comment]
I will check and update as soon as possible.
Thanks for reporting }:]

**Comment by Fausto-Korpsvart** [comment]
> text not visible in gnome settings search results

It's already fixed, you can try it and let me know if you find more errors.
Again, thanks for reporting.
