### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by Magolor44** [Fausto-Korpsvart/Catppuccin-GTK-Theme#26]
After trying to install the Graphite GTK theme after having installed the Catpuccin theme beforehand along the libadwaita theme using `./install.sh -g -l --tweaks float colorful` and logging back in, most GTK4 applications are still themed after the catpuccin theme. I've tried multiple other ways of resetting the GTK theme, like replacing the CSS files again, but it doesn't seem to work.

**Comment by Fausto-Korpsvart** [comment]
> After trying to install the Graphite GTK theme after having installed the Catpuccin theme beforehand along the libadwaita theme using `./install.sh -g -l --tweaks float colorful` and logging back in, most GTK4 applications are still themed after the catpuccin theme. I've tried multiple other ways of resetting the GTK theme, like replacing the CSS files again, but it doesn't seem to work.

You can also use the `-u` parameter to uninstall the theme, or you can check the paths where the themes are installed, these are: in the $HOME folder, the `.themes` directory, in the config folder, the `gtk-4.0` directory; in these two directories you can check if the Catppuccin themes are still installed, remove them and try any other theme of your choice.
