### ISSUE TITLE
Latte theme doesn't match screenshots

### ISSUE THREAD

**Issue by katkauma** [Fausto-Korpsvart/Catppuccin-GTK-Theme#3]
Hello, I love this theme, thank you for making it! 

However, when I use the latte version, it doesn't seem to match the screenshots you provide in the README. Specifically, the light areas are missing or in the wrong spot.  I don't know how to describe it, so I've included screenshots.

I am running ubuntu 21.10, with gtk 3.0.  

Any help would be greatly appreciated!

![image](https://user-images.githubusercontent.com/43046498/189736983-a33ab767-c360-49a7-8950-f64701bb2593.png)
![image](https://user-images.githubusercontent.com/43046498/189736714-fee19b67-ad34-4838-bec2-7caba6fbec10.png)

**Comment by Fausto-Korpsvart** [comment]
> 
That's strange, I've been testing on Ubuntu 22.04 and the same thing happens, but I fixed the error, you must go to the theme folder and find the gtk-3.0 directory and rename the files inside: rename the gtk.css file to gtk-dark.css and the gtk-dark.css file rename it to gtk.css, I don't know why that error happens, but when I have time I'll make an update to fix the error.

Thanks for reporting and your support.

**Comment by katkauma** [comment]
Changing the names fixed the problem, thank you for quick response!
