### ISSUE TITLE
more gnome files changes

### ISSUE THREAD

**Issue by Rishabh-Sarang** [Fausto-Korpsvart/Catppuccin-GTK-Theme#31]
need line break in option menu

![menu1](https://github.com/user-attachments/assets/bb1e8f7e-575f-4733-b322-2459695367a1)
![menu2](https://github.com/user-attachments/assets/553dc31e-d10e-4de4-ab1a-14f7880ac380)
![trash1](https://github.com/user-attachments/assets/d503031c-97aa-4a22-ba0f-0e578eba15ae)
![trash2](https://github.com/user-attachments/assets/38e89ac5-dde0-4dca-a8f5-c761686177eb)

**Comment by Fausto-Korpsvart** [comment]
I'm already working on solving the incompatibilities with Gnome 47, as soon as I can I'll do the update, many things are already solved, but I want to solve everything to do the update, a little patience while it comes.

**Comment by Rishabh-Sarang** [comment]
> I'm already working on solving the incompatibilities with Gnome 47, as soon as I can I'll do the update, many things are already solved, but I want to solve everything to do the update, a little patience while it comes.

Bro where where you past this month
I had to use the default gnome theme

**Comment by Fausto-Korpsvart** [comment]
Theme updated!
