### ISSUE TITLE
Instructions for Mocha Variant

### ISSUE THREAD

**Issue by christoph2497** [Fausto-Korpsvart/Catppuccin-GTK-Theme#33]
Hi I just wanted to ask for instructions how to use the mocha variant. Cause you mention them some earlier changelogs and also the screenshot shows the mocha variant but I can't find the proper files to get it to work.

Any advice would be helpful.

Thanks in advance,

Christoph

**Comment by Fausto-Korpsvart** [comment]
> Hi I just wanted to ask for instructions how to use the mocha variant. Cause you mention them some earlier changelogs and also the screenshot shows the mocha variant but I can't find the proper files to get it to work.
> 
> Any advice would be helpful.
> 
> Thanks in advance,
> 
> Christoph

Sorry for the delay.
`Mocha` is the default version, then you can choose to install `Frappe` and `Macchiatto` for the dark theme versions.
