### ISSUE TITLE
udiskie: Could not find an icon named 'drive-removable-media-usb-panel'

### ISSUE THREAD

**Issue by sonjiku** [Fausto-Korpsvart/Catppuccin-GTK-Theme#34]
Hey!

Thanks a lot for your great work! I really love the theme!

Sad thing is `udiskie` for the tray looks for the `drive-removable-media-usb-panel` icon, but it doesn't seem to exist. I assume it could be linked to `drive-removable-media-usb-symbolic` so this might be an easy fix!

**Comment by Fausto-Korpsvart** [comment]
Could you add some screenshots to understand your description a bit better?

**Comment by sonjiku** [comment]
Lol, I got a bit confused. All is well, and your theme is perfect. I'm closing this issue as it was an issue that was generated by my system and not related to your theme.
