### ISSUE TITLE
Latte theme inverted?

### ISSUE THREAD

**Issue by diorcula** [Fausto-Korpsvart/Catppuccin-GTK-Theme#4]
So i have installed the themes according to the readme.
However, it seems the Latte theme is inverted from the images posted?

![image](https://user-images.githubusercontent.com/32682696/193402654-7aabcb96-3eec-43e1-bb8b-9d05eed599fa.png)

Cheers

**Comment by Fausto-Korpsvart** [comment]
> So i have installed the themes according to the readme. However, it seems the Latte theme is inverted from the images posted?
> 
> ![image](https://user-images.githubusercontent.com/32682696/193402654-7aabcb96-3eec-43e1-bb8b-9d05eed599fa.png)
> 
> Cheers

[Here](https://github.com/Fausto-Korpsvart/Catppuccin-GTK-Theme/issues/3#issuecomment-1244823662) is the temporary solution until I update the theme, sorry for the inconvenience, and thanks for reporting and your support.

**Comment by diorcula** [comment]
The temporary fix worked indeed!
Will close as this is a duplicate issue
