### ISSUE TITLE
Mauve color line in chromium

### ISSUE THREAD

**Issue by ceeeej1141** [Fausto-Korpsvart/Catppuccin-GTK-Theme#5]
I am using the Mocha color palette, but this problem doesn't persist in the private window.
![image](https://user-images.githubusercontent.com/80418063/197700305-b29efb63-a13c-4151-93f6-296f085f6737.png)

**Comment by Fausto-Korpsvart** [comment]
> I am using the Mocha color palette, but this problem doesn't persist in the private window. ![image](https://user-images.githubusercontent.com/80418063/197700305-b29efb63-a13c-4151-93f6-296f085f6737.png)

This is actually not a problem, I tweaked a bit to highlight some lines, icons and texts with the colours of the Mocha palette for Chromium based browsers.
But maybe I'll consider changing the colours again.

**Comment by ceeeej1141** [comment]
> > I am using the Mocha color palette, but this problem doesn't persist in the private window. ![image](https://user-images.githubusercontent.com/80418063/197700305-b29efb63-a13c-4151-93f6-296f085f6737.png)
> 
> This is actually not a problem, I tweaked a bit to highlight some lines, icons and texts with the colours of the Mocha palette for Chromium based browsers. But maybe I'll consider changing the colours again.

I see, I just noticed that it fully works in Firefox but in brave browser the search bar remains orange (default brave color). I actually like this idea but a little bit of improvements are needed. I am thankful that you made this GTK theme since the official one from catppuccin has a problem with chromium. Specifically, it has a transparent line. I thought it was the same from this one but with Mauve color. Anyways, thank you for clarifying.

**Comment by Fausto-Korpsvart** [comment]
> > > I am using the Mocha color palette, but this problem doesn't persist in the private window. ![image](https://user-images.githubusercontent.com/80418063/197700305-b29efb63-a13c-4151-93f6-296f085f6737.png)
> > 
> > 
> > This is actually not a problem, I tweaked a bit to highlight some lines, icons and texts with the colours of the Mocha palette for Chromium based browsers. But maybe I'll consider changing the colours again.
> 
> I see, I just noticed that it fully works in Firefox but in brave browser the search bar remains orange (default brave color). I actually like this idea but a little bit of improvements are needed. I am thankful that you made this GTK theme since the official one from catppuccin has a problem with chromium. Specifically, it has a transparent line. I thought it was the same from this one but with Mauve color. Anyways, thank you for clarifying.

I know what you mean, and you're right, some tweaks are needed, I will try to introduce some changes for the next update.

And yes, someone else also told me that the official GTK theme is a bit abandoned, when I started this theme, I didn't know there was already an official one, and it's good to know that this is a good option for the official theme.

Thanks for your support and for reporting the issue.

**Comment by ceeeej1141** [comment]
> > > > I am using the Mocha color palette, but this problem doesn't persist in the private window. ![image](https://user-images.githubusercontent.com/80418063/197700305-b29efb63-a13c-4151-93f6-296f085f6737.png)
> > > 
> > > 
> > > This is actually not a problem, I tweaked a bit to highlight some lines, icons and texts with the colours of the Mocha palette for Chromium based browsers. But maybe I'll consider changing the colours again.
> > 
> > 
> > I see, I just noticed that it fully works in Firefox but in brave browser the search bar remains orange (default brave color). I actually like this idea but a little bit of improvements are needed. I am thankful that you made this GTK theme since the official one from catppuccin has a problem with chromium. Specifically, it has a transparent line. I thought it was the same from this one but with Mauve color. Anyways, thank you for clarifying.
> 
> I know what you mean, and you're right, some tweaks are needed, I will try to introduce some changes for the next update.
> 
> And yes, someone else also told me that the official GTK theme is a bit abandoned, when I started this theme, I didn't know there was already an official one, and it's good to know that this is a good option for the official theme.
> 
> Thanks for your support and for reporting the issue.

You're Welcome, I am also thankful for the clarification. I'm going to close this now. Please keep it up, and God bless.
