### ISSUE TITLE
Add GNOME 43 support

### ISSUE THREAD

**Issue by sid314** [Fausto-Korpsvart/Catppuccin-GTK-Theme#6]
Some components of GNOME 43's new quick settings aren't properly theme . Add support for them.

**Comment by Fausto-Korpsvart** [comment]
> Some components of GNOME 43's new quick settings aren't properly theme . Add support for them.

That's because I haven't updated the theme to support Gnome 43 yet, I'm working on it and when I have free time I'll update it.
