### ISSUE TITLE
question: selector name

### ISSUE THREAD

**Issue by zettlrobert** [Fausto-Korpsvart/Catppuccin-GTK-Theme#7]
hey there i am currently running pop_os and have installed the beautiful theme.

unfortunately i need to make one small tweak, the default launcher has a text color which is not really readable on it's background(as shown in the screenshot) could you point me in the right direction on how to find out which selector is for what element?

also i assume a change would not apply on saving in one of the css files, is a restart of the gnome session enough?

sorry for my inexperience have not touched shell themes in any way until now.

![image](https://user-images.githubusercontent.com/19976985/215230271-fa2bcddb-3bd2-46aa-8f79-baed9013ba9f.png)

**Comment by Fausto-Korpsvart** [comment]
> hey there i am currently running pop_os and have installed the beautiful theme.
> 
> unfortunately i need to make one small tweak, the default launcher has a text color which is not really readable on it's background(as shown in the screenshot) could you point me in the right direction on how to find out which selector is for what element?
> 
> also i assume a change would not apply on saving in one of the css files, is a restart of the gnome session enough?
> 
> sorry for my inexperience have not touched shell themes in any way until now.
> 
> ![image](https://user-images.githubusercontent.com/19976985/215230271-fa2bcddb-3bd2-46aa-8f79-baed9013ba9f.png)

If I'm not wrong, I think it's related to the selector: `list-search-result:selected`, when I'm at home I'll check it, and when I have some time I'll fix some problems to update.

And don't worry about inexperience, I don't know everything about GTK Themes, I usually always have to go to the documentation to find out how some things work, and when I have time I play trial and error to understand how themes work. Unfortunately for now, thanks to work, I haven't had much time to dedicate to the themes, but it only takes curiosity to learn.

Thanks for your feedback. As soon as I can, I will fix bugs and update.

**Comment by zettlrobert** [comment]
if i find time i will also look into finding said theme, if I manage to find and fix the issue before you do, i will just create a pr!

thanks for your quick response.
