### ISSUE TITLE
fedora37,The desktop background is covered by an accent color

### ISSUE THREAD

**Issue by luxingzhi27** [Fausto-Korpsvart/Catppuccin-GTK-Theme#8]
Hello!
I'm using the fedora 37.When I try to change the theme of gtk4.0, I copy the gtk4.0 file in the theme package folder under ~/.config/gtk4.0/, but my desktop background is covered by the accent color and the app shows fine, like this
![](https://raw.githubusercontent.com/luxingzhi27/picture/main/%E6%88%AA%E5%9B%BE%202023-03-27%2022-48-20.png)

**Comment by Fausto-Korpsvart** [comment]
> ~/.config/gtk4.0/

This has happened to me when I use the blur extension, I don't know why it happens, but it's not the theme that has the problem, it's the extension.
You should also remember that you only have to copy the contents of the `/.themes/Catppuccin-Mocha/gtk-4.0` folder into the `~/.config/gtk4.0/` folder, not the whole directory.
Anyway, I will review the issue, when work allows me, I will resume the project and do a bug fix update.

Thanks for your support.
