### ISSUE TITLE
Want to remove transparency | selector-name

### ISSUE THREAD

**Issue by SagXD** [Fausto-Korpsvart/Catppuccin-GTK-Theme#9]
I want to remove transparency of this (I don't know what it called) Can you please help. I am very new in theming 
<p align="center">
    <img src="https://i.imgur.com/ikX7WBi.png">
</p>

**Comment by SagXD** [comment]
Just tell me selector name.

**Comment by Fausto-Korpsvart** [comment]
> Found out by my self. 👍

Sorry for the delay, but I have been quite busy at work.

This week I hope to resume and will change the transparency to solid by default.

And good that you managed to find the selector, if I remember correctly it's something related to `popovers` to something similar, I don't remember right now, but it better be solid by default, so I hope to work this week on the issues to update as soon as possible.
